# config.yml

# 当确认exploit无误时在exploits中加入脚本名，target为target_groups中的一项
exploits:
  web1-eval:
    target:
      - primary
  web2-lfi:
    target:
      - primary
  web2-unserialize:
    target:
      - primary


# target_groups是想能区分不同的目标。比如有些目标设置了通防，
# 再攻击可能没有意义，那么可以划分为一个target_group
target_groups:
  primary:
    - 127.0.0.1:8000
    - 127.0.0.1:8001
    - 127.0.0.1:8004
    - 127.0.0.1:8005
    - 127.0.0.1:8006
    - 127.0.0.1:8007
    - 127.0.0.1:8008
    - 127.0.0.1:8009
    - 127.0.0.1:8010
    - 127.0.0.1:8011
    - 127.0.0.1:8012
    - 127.0.0.1:8013

# 关于输出格式的一些设置，不用动
print_fmt:
  # .format(target, exp, status, flag)
  single_job: '|{:^20s}|{:^8s}|{:^10s}|{:^10s}'
  banner: 'Exploit'